In [1]:
import torch
from torch import nn

In [2]:
net = nn.Sequential(nn.LazyLinear(8),
                   nn.ReLU(),
                   nn.LazyLinear(1))
X = torch.rand(size=(2, 4))
net(X).shape

/Users/bellaxia/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/lazy.py:178: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


torch.Size([2, 1])

In [3]:
net[2].state_dict()

OrderedDict([('weight',
              tensor([[ 0.0644,  0.1184,  0.1701,  0.3249,  0.1386, -0.3278,  0.2892,  0.2266]])),
             ('bias', tensor([-0.1237]))])

In [4]:
net[0].state_dict()

OrderedDict([('weight',
              tensor([[ 0.2385, -0.4076, -0.0276,  0.1542],
                      [-0.0022, -0.0531,  0.2723,  0.1230],
                      [ 0.1858,  0.3858,  0.3302, -0.4807],
                      [-0.3114,  0.3061, -0.1725, -0.2462],
                      [-0.1449, -0.1884,  0.1333, -0.3969],
                      [ 0.0534, -0.3191,  0.2525,  0.1857],
                      [-0.3436,  0.3304, -0.0399, -0.2159],
                      [ 0.4133,  0.1604,  0.1152,  0.4287]])),
             ('bias',
              tensor([-0.3182, -0.3426,  0.4260,  0.4848,  0.4593, -0.4017, -0.3312,  0.3109]))])

In [5]:
net[1].state_dict()

OrderedDict()

In [6]:
type(net[2].bias.data), net[2].bias.data

(torch.Tensor, tensor([-0.1237]))

In [7]:
net[2].weight.grad==None

True

In [8]:
[(name, param.shape) for name, param in net.named_parameters()]

[('0.weight', torch.Size([8, 4])),
 ('0.bias', torch.Size([8])),
 ('2.weight', torch.Size([1, 8])),
 ('2.bias', torch.Size([1]))]

In [9]:
shared = nn.LazyLinear(8)
net = nn.Sequential(nn.LazyLinear(8), nn.ReLU(),
                   shared, nn.ReLU(),
                   shared, nn.ReLU(),
                   nn.LazyLinear(1))

In [10]:
net(X)

tensor([[0.3533],
        [0.3502]], grad_fn=<AddmmBackward0>)

In [11]:
print(net[2].weight.data[0] == net[4].weight.data[0])

tensor([True, True, True, True, True, True, True, True])


In [12]:
net[2].weight.data[0, 0] = 100
print(net[2].weight.data[0] == net[4].weight.data[0])

tensor([True, True, True, True, True, True, True, True])
